# Use postgres/example user/password credentials
version: '3.1'
networks:
  beneficiaries-net:
    driver: "bridge"
    name: beneficiaries-net
    
services:
  beneficiaries-db:
    image: postgres:13-alpine
    container_name: beneficiaries_db
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: beneficiaries
    volumes:
      - C:/Users/IgnacioGabrielSamped/Documents/PF/.db:/var/lib/postgresql/data
    ports:
      - 5434:5432
    networks:
      - beneficiaries-net

  beneficiaries:
    image: ghcr.io/mamis-solidarias/beneficiaries:main
    restart: unless-stopped
    depends_on:
      - beneficiaries-db
    ports:
      - 81:80
      - 444:443
    networks:
      - beneficiaries-net
    environment:
      ASPNETCORE_ENVIRONMENT: development
      ConnectionStrings__Production: 'Host=beneficiaries_db:5432;Database=beneficiaries;Username=dev;Password=dev'
      ConnectionStrings__Development: 'Host=beneficiaries_db:5432;Database=beneficiaries;Username=dev;Password=dev'
      JWT__Key: 'Super long key no one will ever find out and definitely not typed by hand'
      
