name: Lint

on:
  pull_request:
    branches: [ "main" ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install JS dependencies
        run: yarn install
        
      - run: ls .
      - run: npm run lint
